/*
 * This source file was generated by the Gradle 'init' task
 */
package nsu.frquency_parser;

import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {
    // One test that always make you happy.
    @Test 
    public void TestAllwaysOk() {
        assertTrue(true);
    }
}
