/*
 * This source file was generated by the Gradle 'init' task
 */
package nsu.frequency_parser;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;

public class App {
    @Parameter(names = {"--input", "-i"}, description = "Input file", required = true) 
    private String inputFile;

    @Parameter(names = {"--output", "-o"}, description = "Output file", required = true)
    private String outputFile;

    @Parameter(names = "--help", help = true) boolean help;
    
    public static void main(String[] args) {
        var app = new App();

        JCommander jc = JCommander.newBuilder()
                .addObject(app)
                .build();
        
        if (args.length == 0 || app.help) {
            jc.usage();
            return;
        }

        jc.parse(args);

        app.run();
    }

    public void run() {
        try {
            WordsFrequencyAnalizer.Analize(new FileReader(inputFile), new FileWriter(outputFile));
        } catch (FileNotFoundException e) {
            System.err.println(String.format("Fail parsing %s with %s - %s", 
                inputFile,  
                e.getClass().getName(), 
                e.getMessage()));
        } catch (IOException e) {
            System.err.println(String.format("Fail parsing %s with %s - %s", 
                inputFile,  
                e.getClass().getName(), 
                e.getMessage()));
        }
    }
}
